const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./src/data/cities.json', 'utf8'));

const origins = {
  "tokyo": { founded: "1457", originalName: "Edo", founders: "Ōta Dōkan, a samurai lord", story: "Ōta Dōkan built a modest castle on the marshy lowlands of Musashino in 1457, calling it Edo. For over a century it remained a minor outpost until Tokugawa Ieyasu chose it as his shogunate capital in 1603, triggering the most dramatic urban expansion in Japanese history. When Emperor Meiji moved from Kyoto in 1868 and renamed it Tokyo — Eastern Capital — the city of one million became the beating heart of a modernising empire.", era: "Medieval" },
  "istanbul": { founded: "circa 657 BCE", originalName: "Byzantium", founders: "Greek colonists led by Byzas of Megara", story: "Greek legend says Byzas consulted the Oracle at Delphi, who told him to settle 'opposite the land of the blind' — a jibe at earlier settlers who had missed the supreme natural harbour on the European shore. Constantine the Great rebuilt it as Constantinople in 330 CE and declared it the new Rome. After 1,000 years as the heart of the Byzantine Empire, Mehmed II conquered it in 1453 at age 21, armed with the world's largest cannons.", era: "Ancient" },
  "new-york": { founded: "1626", originalName: "New Amsterdam", founders: "Dutch West India Company", story: "Peter Minuit of the Dutch West India Company purchased Manhattan from the Lenape people in 1626 for 60 guilders' worth of trade goods. The Dutch built a fort at its southern tip and called it New Amsterdam. Britain seized it without a fight in 1664 and renamed it New York after the Duke of York — and the city has never looked back since.", era: "Colonial" },
  "paris": { founded: "circa 250 BCE", originalName: "Lutetia", founders: "The Celtic Parisii tribe", story: "The Celtic Parisii settled on an island in the Seine — today's Île de la Cité — around 250 BCE. Julius Caesar's legions conquered it in 52 BCE after a fierce Gallic revolt. The city grew into one of Europe's greatest medieval centres of learning, and by the time Baron Haussmann bulldozed its medieval alleys in the 1850s to create grand boulevards, Paris had already been reshaping Western civilisation for 2,000 years.", era: "Ancient" },
  "mumbai": { founded: "1534", originalName: "Bombaim", founders: "Portuguese colonial forces", story: "For millennia, seven marshy islands off India's western coast were home to the Koli fishing people who called the bay Mumba Aai after their goddess. The Portuguese arrived in 1534 and dubbed it Bombaim — good little bay. In 1661 the islands were given to King Charles II of England as part of his Portuguese bride's dowry, then leased to the East India Company for a symbolic ten pounds per year. The British gradually linked the islands by land reclamation, and the resulting city became the financial engine of the entire subcontinent.", era: "Colonial" },
  "rio-de-janeiro": { founded: "1565", originalName: "São Sebastião do Rio de Janeiro", founders: "Estácio de Sá, Portuguese conquistador", story: "On New Year's Day 1502, navigator Gaspar de Lemos sailed into Guanabara Bay and mistook it for a great river — naming it Rio de Janeiro, River of January. The city was formally founded on March 1, 1565. For two centuries it was a colonial backwater until the Portuguese royal family fled Napoleon and made it the capital of their empire in 1808 — the only time a European monarch governed from the New World.", era: "Colonial" },
  "marrakech": { founded: "1070", founders: "Abu Bakr ibn Umar of the Almoravid dynasty", story: "Abu Bakr ibn Umar, leader of the Almoravid Berber dynasty sweeping north from the Sahara, founded Marrakech in 1070 as his base for conquering Morocco and southern Spain. Its legendary souks, tanneries, and the Djemaa el-Fna square — a UNESCO Intangible Cultural Heritage site — have operated continuously for nearly a thousand years, making Marrakech one of the world's most intact medieval urban environments.", era: "Medieval" },
  "sydney": { founded: "1788", originalName: "Warrane (Eora name)", founders: "Captain Arthur Phillip, British First Fleet", story: "On January 26, 1788, Captain Arthur Phillip sailed 11 ships into Port Jackson — the finest natural harbour he had ever seen — carrying 1,487 people, more than half of them convicts. The Eora Aboriginal people had lived on these shores for at least 60,000 years. Phillip raised the Union Jack and named the settlement after Thomas Townshend, Lord Sydney. What began as a penal colony became, within a century, one of the most prosperous cities in the Southern Hemisphere.", era: "Colonial" },
  "amsterdam": { founded: "circa 1270", founders: "Fishing communities who dammed the Amstel River", story: "Around 1270, fishermen and farmers built a dam across the Amstel River where it met the IJ bay — creating the Amstelredamme. The city received its charter around 1306. Then came the Dutch Golden Age: by the 1630s Amsterdam was the wealthiest city on Earth, home to Rembrandt, the world's first stock exchange, and trading ships connecting every inhabited continent.", era: "Medieval" },
  "barcelona": { founded: "circa 15 BCE", originalName: "Barcino", founders: "Roman Emperor Augustus's legions", story: "Roman soldiers established the colony of Barcino around 15 BCE on a small hill called Mons Taber — some of those original Roman walls still stand in the Gothic Quarter today. After centuries of Visigoth and Moorish rule, Barcelona became capital of the County of Catalonia, a Mediterranean power whose Crown of Aragon once controlled Sicily, Sardinia, and parts of Greece.", era: "Ancient" },
  "seoul": { founded: "1394", originalName: "Hanyang (漢陽)", founders: "King Taejo of the Joseon dynasty", story: "In 1394, King Taejo of the newly founded Joseon dynasty chose a mountain-ringed valley on the Han River as his capital, naming it Hanyang. Geomancers declared the site — embraced by four guardian mountains — ideally suited for a ruling dynasty. After Japanese occupation and the devastating Korean War, Seoul rebuilt itself into one of the most technologically advanced megacities on Earth within a single generation.", era: "Medieval" },
  "singapore": { founded: "1819", originalName: "Singapura", founders: "Sir Stamford Raffles, British East India Company", story: "Ancient Malay texts describe a lion-sighting here around 1299 — prompting the name Singapura, Lion City in Sanskrit, though no lions ever lived there. Sir Stamford Raffles stepped ashore on February 6, 1819 and signed a treaty to establish a British trading post. Within five years the free port had 10,000 residents; within fifty years it was the busiest port east of Suez.", era: "Colonial" },
  "dubai": { founded: "1833", founders: "The Al Maktoum family and 800 members of the Bani Yas tribe", story: "In 1833, some 800 members of the Bani Yas tribe settled at the mouth of the Dubai Creek under the Al Maktoum family — a dynasty that rules to this day. For over a century Dubai earned its living from pearl diving and creek trading. Oil was discovered offshore in 1966, and Sheikh Rashid made a calculated bet: use the oil wealth to build infrastructure, then use the infrastructure to outlast the oil. It worked beyond all expectation.", era: "Modern" },
  "london": { founded: "43 CE", originalName: "Londinium", founders: "Roman Emperor Claudius's invasion force", story: "Roman forces built a bridge across the Thames in 43 CE and established Londinium as a supply hub. Within 17 years it was the province's largest city — until Queen Boudica of the Iceni tribe burned it to the ground in 60 CE, an act so total that archaeologists can still identify its ash layer beneath modern London. The Romans rebuilt it grander than before, and the outline of its walls still shapes central London's street plan today.", era: "Ancient" },
  "kyoto": { founded: "794 CE", originalName: "Heian-kyō (平安京)", founders: "Emperor Kanmu of Japan", story: "Emperor Kanmu chose this mountain-ringed valley in 794 CE and named it Heian-kyō — Capital of Peace and Tranquility — modelling it on Tang Dynasty Chang'an. For over 1,000 years every Japanese emperor lived here, and the court culture produced The Tale of Genji, the world's first novel. When Emperor Meiji moved to Tokyo in 1869, Kyoto lost its political role but retained its soul: 1,600 Buddhist temples and Shinto shrines still stand.", era: "Medieval" },
  "cape-town": { founded: "1652", originalName: "Camissa", founders: "Jan van Riebeeck, Dutch East India Company (VOC)", story: "The indigenous Khoikhoi called this place Camissa — place of sweet waters. On April 6, 1652, Jan van Riebeeck arrived with three ships to build a refreshment station for VOC ships rounding the Cape of Good Hope — not a colony, his orders said, just a garden and a fort. Within decades it had become a full colony, and the convergence of Khoikhoi, Dutch, Malay, and British populations created South Africa's most culturally layered city.", era: "Colonial" },
  "bangkok": { founded: "1782", originalName: "Krung Thep (กรุงเทพ)", founders: "King Rama I of the Chakri dynasty", story: "After Ayutthaya fell to Burmese forces in 1767, King Rama I established a fresh capital on April 21, 1782, choosing a bend in the Chao Phraya River. He named it Krung Thep, City of Angels — though its full ceremonial name runs to 168 letters, the world's longest place name. Westerners adopted the name of a riverside village, Bang Makok, corrupting it into Bangkok.", era: "Modern" },
  "mexico-city": { founded: "1325", originalName: "Tenochtitlán", founders: "The Mexica (Aztec) people", story: "An Aztec prophecy said to found their city where they saw an eagle on a cactus eating a serpent. In 1325, they found the sign on an island in Lake Texcoco and built Tenochtitlán, which grew to 200,000 people. Hernán Cortés arrived in 1519 and by 1521 had razed it entirely. The Spanish rebuilt their capital on its ruins, draining the lake over centuries — which is why modern Mexico City slowly sinks into ancient lakebed.", era: "Medieval" },
  "new-orleans": { founded: "1718", founders: "Jean-Baptiste Le Moyne de Bienville, French colonial governor", story: "In 1718, French governor Bienville chose a horseshoe bend in the Mississippi despite his engineers warning it was a swamp that flooded regularly. Napoleon sold the territory to the United States in 1803 as part of the Louisiana Purchase — the fifteen million dollar deal that doubled America's size. The city's unique culture, a fusion of French, Spanish, African, and Caribbean influences, has never fully belonged to any single nation.", era: "Colonial" },
  "rome": { founded: "circa 753 BCE", founders: "Romulus (mythological) / Latin and Sabine tribes (historical)", story: "Roman tradition holds that Romulus founded the city on April 21, 753 BCE, after killing his twin brother Remus in a dispute about which hill to build on — the Palatine won. From a hilltop village, Rome became a republic, then an empire controlling 5 million square kilometres. When that empire fell, its language, law, and religion shaped every European civilisation that followed.", era: "Ancient" },
  "vienna": { founded: "circa 15 BCE", originalName: "Vindobona", founders: "Roman legions under Emperor Augustus", story: "Roman legions built the military fortress Vindobona around 15 BCE to guard the Danube frontier — Emperor Marcus Aurelius died within its walls in 180 CE while writing his Meditations. The Habsburgs made it the capital of an empire ruling Central Europe for 640 years. By 1900 Vienna was home to Freud, Klimt, Mahler, and Wittgenstein — a concentration of genius so dense that Stefan Zweig called it the city of his dreams.", era: "Ancient" },
  "prague": { founded: "circa 880 CE", originalName: "Praha", founders: "The Přemyslid dynasty", story: "Czech legend says the princess Libuše stood on a cliff above the Vltava and proclaimed: 'I see a great city whose glory will touch the stars!' She commanded that it be founded where workers found a man carving a doorstep — práh in Czech — giving Prague its name. Under Charles IV in the 14th century it became the capital of the Holy Roman Empire. Its medieval core survived two world wars intact, making it one of the best-preserved Gothic and Baroque cities on Earth.", era: "Medieval" },
  "budapest": { founded: "1873 (unified); Roman Aquincum circa 89 CE", originalName: "Aquincum (Roman) / Buda and Pest (medieval)", founders: "Roman legions; unified by the Austro-Hungarian government", story: "Two separate cities — Buda on the hilly west bank of the Danube and the flat commercial Pest on the east — were formally merged on November 17, 1873. Buda's Castle Hill has been fortified since Celtic times and the Romans built their provincial capital Aquincum here in 89 CE. Devastated by Mongol invasion in 1241 and Ottoman occupation from 1541 to 1686, it rebuilt grander each time, emerging in the late 19th century as one of Europe's most lavishly architected capitals.", era: "Ancient" },
  "lisbon": { founded: "circa 1200 BCE", originalName: "Allis Ubbo", founders: "Phoenician traders", story: "Phoenician traders called this hilltop above the Tagus estuary Allis Ubbo — calm harbour — around 1200 BCE, one of the finest natural ports on the Atlantic coast. Romans captured it in 205 BCE, and in 1147 Portugal's first king took it from the Moors. Then Vasco da Gama sailed from these shores in 1497 and opened the sea route to India, making Lisbon briefly the richest city on Earth as the hub of a global spice empire.", era: "Ancient" },
  "berlin": { founded: "1237", founders: "Settlers establishing twin market towns — Berlin and Cölln — on the River Spree", story: "Two small merchant towns — Berlin and Cölln — on islands in the River Spree are first recorded in 1237. They grew as a Hanseatic trading centre and in 1701 became the capital of the Kingdom of Prussia. The 20th century made Berlin the stage for history's most dramatic acts: the Wall went up in 1961 and fell on November 9, 1989 — a single night that changed the world. Today the city wears its scars as art.", era: "Medieval" },
  "athens": { founded: "circa 3000 BCE", founders: "Prehistoric Aegean peoples; mythologically by the goddess Athena", story: "The Acropolis rock has been continuously inhabited since at least 3000 BCE. Ancient myth says Athena won the city by offering the olive tree, defeating Poseidon's gift of a saltwater spring. Under Cleisthenes in 508 BCE it became the world's first democracy, and under Pericles it built the Parthenon and produced Socrates, Plato, Aristotle, Sophocles, and Herodotus within a single remarkable century. The words politics, democracy, philosophy, and theatre all originated here.", era: "Ancient" },
  "hong-kong": { founded: "1841 (British); inhabited for millennia", originalName: "Heung Gong — Fragrant Harbour", founders: "Yue people (ancient); British forces under Captain Charles Elliot (colonial era)", story: "The Cantonese name Heung Gong — Fragrant Harbour — describes an island the Yue people had farmed and fished for thousands of years. British forces occupied it during the First Opium War in 1841, and it was formally ceded under the Treaty of Nanking in 1842. On July 1, 1997, in a midnight ceremony watched by billions, Hong Kong was handed back to China after 155 years of British rule.", era: "Colonial" },
  "taipei": { founded: "1709 (Han Chinese settlement); capital 1887", founders: "Han Chinese settlers from Fujian; formalised by Qing Dynasty governor Liu Mingchuan", story: "Han Chinese settlers from Fujian began farming the fertile Taipei Basin around 1709, gradually displacing the indigenous Ketagalan people. In 1887, Qing Dynasty governor Liu Mingchuan declared it the provincial capital and began modernising it with railways and telegraph. Japan controlled Taiwan from 1895 to 1945, leaving a legacy of orderly urban planning and colonial buildings. The Nationalist government arrived in 1949, turning it into the capital of the Republic of China.", era: "Modern" },
  "osaka": { founded: "circa 645 CE (as Naniwa); modern form 1583", originalName: "Naniwa (難波)", founders: "Emperor Kōtoku (ancient); Toyotomi Hideyoshi (modern era)", story: "Naniwa served as Japan's first proper imperial capital under Emperor Kōtoku in 645 CE, before Nara and Kyoto took that role. In 1583, the warlord Toyotomi Hideyoshi built his great castle here and declared Osaka Japan's commercial centre. Merchants, not samurai, shaped Osaka's soul — and to this day its people are famous for their blunt practicality and obsession with food. The city's informal motto is kuidaore: eat until you drop.", era: "Ancient" },
  "ho-chi-minh": { founded: "1698 (Vietnamese); earlier Khmer settlement", originalName: "Prey Nokor (Khmer) / Gia Định / Saigon", founders: "Nguyễn Hữu Cảnh, Vietnamese general", story: "Khmer fishermen called this Mekong Delta confluence Prey Nokor — forest city. Vietnamese settlers moved south in the late 17th century and in 1698 the Nguyễn lords formally established the settlement as Gia Định. The French made it the colonial capital of Cochinchina in 1859 and renamed it Saigon, building wide boulevards and neoclassical buildings still visible today. After April 30, 1975, the city was renamed Ho Chi Minh City — though locals still call it Saigon.", era: "Colonial" },
  "buenos-aires": { founded: "1580 (permanent); first attempt 1536", originalName: "Ciudad de la Santísima Trinidad y Puerto de Nuestra Señora de los Buenos Aires", founders: "Pedro de Mendoza (1536); Juan de Garay (permanent founding 1580)", story: "Spanish conquistador Pedro de Mendoza landed on the Río de la Plata shores on February 2, 1536. The Querandí people's attacks forced the Spanish to abandon it within five years; Juan de Garay re-founded it permanently in 1580. For two centuries it was a minor outpost barred from trading directly with Europe. Independence in 1816 and massive European immigration from 1880 to 1930 transformed it into the Paris of South America.", era: "Colonial" },
  "toronto": { founded: "1793 (British fort); city 1834", originalName: "Toronto (Mohawk: where there are trees in the water)", founders: "Lieutenant Governor John Graves Simcoe; indigenous peoples for millennia before", story: "The Haudenosaunee and Anishinaabe peoples had lived at this Lake Ontario site for thousands of years. British Lieutenant Governor Simcoe established Fort York here in 1793 and named it York. American forces burned it to the ground in 1813 — the most significant US military action on Canadian soil. Renamed Toronto in 1834, it grew through waves of immigration into what surveys consistently rank as the world's most ethnically diverse city.", era: "Colonial" },
  "chicago": { founded: "1833 (town); 1837 (city)", originalName: "Shikaakwa (Potawatomi: wild leeks)", founders: "Indigenous Potawatomi people (original); Fort Dearborn established 1803 by US Army", story: "The Potawatomi name Shikaakwa described this river portage between the Great Lakes and the Mississippi for centuries. The US Army built Fort Dearborn in 1803; the town incorporated in 1833 with just 350 residents. The Great Chicago Fire of 1871 burned the city to the ground in 36 hours — and the architects who arrived to rebuild it invented the skyscraper, creating the modern city form that now defines every major metropolis on Earth.", era: "Modern" },
  "miami": { founded: "1896", founders: "Henry Flagler (railway magnate) and Julia Tuttle (settler who convinced him)", story: "The Tequesta people lived at the Miami River mouth for thousands of years before Spanish explorers arrived. The modern city was born from a quirk of agriculture: the Great Freeze of 1894–95 destroyed Florida's citrus crops — except Julia Tuttle's grove in the south. She sent fresh orange blossoms to railroad tycoon Flagler, convincing him to extend his railway south. Miami incorporated on July 28, 1896 with 300 residents — the only major American city founded by a woman.", era: "Modern" },
  "los-angeles": { founded: "1781", originalName: "El Pueblo de la Reina de Los Ángeles", founders: "44 settlers recruited from Sinaloa and Sonora, New Spain", story: "On September 4, 1781, Governor Felipe de Neve led 44 settlers — mostly of African and indigenous Mexican descent — to found El Pueblo de la Reina de Los Ángeles. It remained a dusty ranching village for most of the next century. Oil was discovered in the 1890s, the film industry arrived in the 1910s fleeing Thomas Edison's patent lawsuits in New York, and the aqueduct brought Sierra Nevada water in 1913. The rest, as they say, is Hollywood.", era: "Colonial" },
  "cairo": { founded: "969 CE (Al-Qahira); ancient Memphis nearby circa 3100 BCE", originalName: "Al-Qāhira — The Victorious", founders: "Jawhar al-Siqilli, general of the Fatimid Caliphate", story: "The Fatimid general Jawhar al-Siqilli founded Al-Qahira — The Victorious — in 969 CE as his imperial capital. Al-Azhar mosque, built in 970 CE, became the world's oldest continuously operating university. The site itself is ancient: nearby Memphis was the pharaonic capital from around 3100 BCE, and the Giza pyramids visible from Cairo's western edge were already 2,500 years old when Caesar visited Cleopatra.", era: "Medieval" },
  "nairobi": { founded: "1899", originalName: "Enkare Nairobi (Maasai: cool waters)", founders: "British East Africa Protectorate, as Railway Mile 327 camp", story: "Nairobi was born from a railway camp. In 1899, the British Uganda Railway — nicknamed the Lunatic Express — reached Mile 327 and workers stopped to resupply at a Maasai spring called Enkare Nairobi, cool waters. The British decided to make it a depot, and within eight years it was the colonial capital of British East Africa — one of the only major cities on Earth not established on an ancient settlement or natural harbour, but purely because of a train schedule.", era: "Modern" },
  "edinburgh": { founded: "circa 600 CE", originalName: "Din Eidyn", founders: "The Gododdin, Brittonic Gaelic people of southern Scotland", story: "The volcanic Castle Rock has been fortified since at least 600 CE, when the Brittonic people called it Din Eidyn — fortress of Eidyn. Scotland's capital since the 15th century, the city developed two distinct identities: the medieval Old Town clinging to Castle Rock, and the Georgian New Town built from the 1760s. In a single century this city produced Adam Smith, David Hume, James Watt, and Walter Scott — the Scottish Enlightenment punching far above Scotland's weight.", era: "Medieval" },
  "havana": { founded: "1519", originalName: "San Cristóbal de La Habana", founders: "Diego Velázquez de Cuéllar, Spanish conquistador", story: "Diego Velázquez founded Havana in 1519 after two failed earlier locations. Its extraordinary natural harbour quickly made it the assembly point for Spain's treasure fleet: every year, galleons loaded with Aztec gold and Incan silver gathered here before crossing the Atlantic. For 300 years, virtually all New World wealth flowed through this port. The British captured it briefly in 1762, using it to trade 10,000 enslaved Africans into Cuba — permanently transforming the island's culture.", era: "Colonial" },
  "copenhagen": { founded: "1167 (fortified); settlement circa 1000 CE", originalName: "Køpmannæhafn — Merchants' Harbour", founders: "Bishop Absalon of Roskilde", story: "A fishing settlement called Havn existed on this strait between Denmark and Sweden from around 1000 CE, growing rich on the herring trade. In 1167, Bishop Absalon built a fort on the island of Slotsholmen to protect it from pirates — the act traditionally considered Copenhagen's founding. Denmark's capital since 1443, it was besieged, bombed by the British in 1807, and occupied by Nazi Germany in WWII, yet its centuries-old waterfront remains remarkably intact.", era: "Medieval" },
  "nagano": { founded: "642 CE (Zenkoji Temple); city status 1897", founders: "Buddhist monks who established Zenkoji Temple", story: "Nagano's identity was shaped not by a castle or a trading post, but by a temple. Zenkoji, founded in 642 CE, became one of Japan's most revered pilgrimage sites, housing what is believed to be Japan's first Buddha statue — brought from Korea in 552 CE. Its policy of welcoming all Buddhist sects made Nagano a rare open city in feudal Japan. In 1998, the Winter Olympics introduced the world to Nagano's other treasure: wild macaques soaking in hot springs surrounded by snow.", era: "Medieval" },
  "monterrey": { founded: "1596", founders: "Diego de Montemayor with 12 Spanish families", story: "On September 20, 1596, Spanish captain Diego de Montemayor founded this mountain valley settlement, naming it after the Count of Monterrey, then Viceroy of New Spain. For most of its history it was a modest colonial town. The transformation came in 1890 when Mexico's first steel mill and the Cervecería Cuauhtémoc brewery were established here, turning Monterrey into Mexico's industrial capital — a reputation it holds today as the country's wealthiest and most business-minded city.", era: "Colonial" },
  "los-cabos": { founded: "circa 10,000 BCE (Pericú people); municipality 1981", originalName: "Land of the Pericú people", founders: "Pericú indigenous people (ancient); Dominican missionaries established San José del Cabo in 1730", story: "The Pericú people inhabited the dramatic tip of Baja California for at least 10,000 years. Spanish conquistadors arrived in 1535 but the harsh terrain defeated every colonisation attempt. Dominican missionaries established San José del Cabo in 1730. The two towns existed in near-isolation for centuries until the Transpeninsular Highway in 1973 and the international airport in 1981 opened the cape to the world.", era: "Ancient" },
  "mazunte": { founded: "Pre-Columbian; cooperative community reinvented post-1990", originalName: "Mazuntén (Zapotec: place where the turtle is worshipped)", founders: "Zapotec and Chatino peoples; reinvented as cooperative ecotourism community in 1990", story: "The Zapotec name Mazuntén — place where the turtle is worshipped — reveals millennia of relationship between this Oaxacan coastal village and the sea turtles that nest on its beaches. In the 20th century a government plant harvested up to 100,000 turtles annually. When the federal ban came in 1990 the entire village economy collapsed overnight. What happened next is remarkable: the community reinvented itself as one of Latin America's most celebrated examples of community-led ecotourism and environmental recovery.", era: "Ancient" },
  "new-delhi": { founded: "1911 (planned); inaugurated 1931", founders: "British Indian government; architects Edwin Lutyens and Herbert Baker", story: "In December 1911, King George V announced that India's capital would move from Calcutta to Delhi — a city that had already served as the capital of at least seven previous empires. Architects Lutyens and Baker spent 20 years designing the new imperial capital with monumental avenues radiating from Raisina Hill. New Delhi was formally inaugurated on February 13, 1931 — just sixteen years before the British departed, making it history's most lavishly built short-term colonial capital.", era: "Modern" },
  "varanasi": { founded: "circa 1200 BCE", originalName: "Kashi (काशी) — City of Light", founders: "Attributed to the god Shiva in tradition; historically settled by ancient Aryan peoples", story: "Varanasi is among the oldest continuously inhabited cities on Earth, with settlement traceable to at least 1200 BCE — older than Rome, older than Athens. Hindus call it Kashi, City of Light, and believe that dying here guarantees moksha, liberation from the cycle of rebirth. Mark Twain wrote of it: 'Benares is older than history, older than tradition, older even than legend, and looks twice as old as all of them put together.'", era: "Ancient" },
  "ahmedabad": { founded: "1411", founders: "Sultan Ahmad Shah I of the Gujarat Sultanate", story: "Legend says Sultan Ahmad Shah I was encamped on the Sabarmati River banks in 1411 when he saw a rabbit turn on and chase a hunting dog — taking it as an omen that even the weak become strong here. He named his new capital Ahmedabad after himself. The city grew into one of India's great textile centres, and Mahatma Gandhi chose it as his base for the independence campaign, launching the Dandi Salt March from his Sabarmati Ashram in 1930. In 2017 it became India's first UNESCO World Heritage City.", era: "Medieval" },
  "saitama": { founded: "2001 (current city); inhabited since prehistoric times", originalName: "Musashino Province (武蔵国)", founders: "Current city formed by merger of Urawa, Omiya, and Yono cities on May 1, 2001", story: "The Saitama region formed part of ancient Musashino Province, one of the heartland territories of early Japan — human habitation here stretches back over 20,000 years. Omiya, one of its component towns, grew around Hikawa Shrine, one of Japan's oldest and most revered Shinto sites. The modern city was created on May 1, 2001, when three neighbouring cities merged by administrative consolidation. It is best known for its spectacular cherry blossoms along the Edo River in Satte, drawing visitors from across greater Tokyo.", era: "Contemporary" }
};

let updated = 0;
for (const city of data) {
  if (origins[city.slug]) {
    city.origin = origins[city.slug];
    updated++;
  }
}

fs.writeFileSync('./src/data/cities.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + '/' + data.length + ' cities with origin data');
